### PR TITLE
Define 'invited individual'

### PR DESCRIPTION
**Pull request by travisleithead**
This PR will merge to the 'invited-expert' branch and formalizes the term "invited individual". It also uses the new definition in one place that was appropriate. Note, this term can also be referenced in the related policy document.

### CODE REVIEW

**Review by annevk — APPROVED** [review]
This looks good to me. Thanks!

**Comment by foolip** [comment]
I'll go ahead an merge this so that I can then make additional updates for https://github.com/whatwg/participate.whatwg.org/pull/144.

**Comment by foolip** [comment]
I shouldn't have merged this into https://github.com/whatwg/participate.whatwg.org/pull/144, it wasn't part of the final drafts I was working from. I didn't notice because it doesn't touch any of the same bits as were updated in those drafts. I'll reopen and revert this from https://github.com/whatwg/participate.whatwg.org/pull/144 to have everything match up.

**Comment by foolip** [comment]
Hmm, it seems like it's not possible to reopen. I'll create a new PR instead.

**Pull request merged**
