### PR TITLE
Meta: migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by foolip**
Part of https://github.com/whatwg/meta/issues/173.

### CODE REVIEW

**Comment by foolip** [comment]
@domenic this isn't far from working, but there's one detail to sort out I'd like your input on, on how sg/db.json is deployed.

As it is (before this change), `npm install` will clone or update the sg repository. In addition, deploy.sh does `npm run update-sg` to do the same step. The sg/db.json file thus checkout out is rsynced to the server. Then `npm install --production` is run on the serve, but that will fail because the sg directory exists, but it isn't a git repo:
https://travis-ci.org/github/whatwg/participate.whatwg.org/builds/693501118

Another silent failure mode is likely if changing things a bit, namely that one has a checkout out the participate.whatwg.org repo but the sg/ directory is just a directory. The `git -C sg pull` command would then succeed, but because it updated the participate.whatwg.org repo.

What should we do? The most elaborate/fanciful would be to release sg/db.json as an npm package and depend on that.

**Comment by domenic** [comment]
I don't have strong feelings about how we get `sg.json`; per https://github.com/whatwg/participate.whatwg.org/pull/100 I only used Git to fetch it because that was slightly easier. If it makes things simpler to change `npm run update-sg` to curl https://raw.githubusercontent.com/whatwg/sg/master/db.json, then we should switch to that.

I'm also OK removing the postinstall step. In that case let's just update the README to note that you need to run `npm run update-sg` in addition to `npm install`.

I don't think we need to publish the SG data as an npm package :).

**Comment by domenic** [comment]
@foolip ping on finishing this up :)

**Comment by foolip** [comment]
@domenic I've sent https://github.com/whatwg/participate.whatwg.org/pull/125 which I think should fix the broken deploy on Travis. I'm hopeful that combined with this, everything should then work.

**Comment by foolip** [comment]
Things look good. Let's see if the actual deploy works by merging this, then. I'll switch the branch protection around too.

**Comment by domenic** [comment]
Something wrong with the key-loading... feel free to force-push until it works, assuming the changes are minimal.

**Comment by foolip** [comment]
https://github.com/whatwg/participate.whatwg.org/runs/866280929?check_suite_focus=true failed because I named the secrets incorrectly.

**Comment by foolip** [comment]
Fixed in https://github.com/whatwg/participate.whatwg.org/pull/126 (not force pushed, as I wasn't entirely sure you meant the master branch.

The new failure I think is because the secrets point to the wrong droplet. Fixing.

**Comment by foolip** [comment]
Alright, it's now deployed and seems to work as usual.

**Comment by domenic** [comment]
Awesome, thanks!

**Pull request merged**
