### PR TITLE
Remove everything related to the old hosting setup

### PR DESCRIPTION
**Pull request by foolip**
This removes the ability to serve /version from a version.txt file in
favor of just using the environment variable.

### CODE REVIEW

**Review by domenic — APPROVED** [review]
The lockfile change is larger than I'd expect; did you do `npm install --production` locally instead of `npm install`? Otherwise LGTM

**Comment by foolip** [comment]
@domenic sorry I should have flagged that in the commit message. I looked at reverting 697ded32c2ba6a2101250d97a78324d514ddd0f9 and spotted that it made a large change to the lockfile, changing it from `lockfileVersion` 1 to 2. I'd also seen warning about this in the image build step, so I deleted `package-lock.json` and regenerated it entirely.

**Comment by domenic** [comment]
Yeah, I'm using a newer npm version locally. I guess if it's regenerated from scratch then it's trustworthy, I just wonder whether the large delta is because of differences in npm versions or differences in what we ended up installing.

**Comment by foolip** [comment]
Comparing to the `package-lock.json` at commit c47b10c7a90c384b741b14f84c36d540b8d000d4 (parent of https://github.com/whatwg/participate.whatwg.org/commit/697ded32c2ba6a2101250d97a78324d514ddd0f9) the changes are small and typical of a few bumped dependencies, so it looks like the big difference is due to the lockfile version.

**Comment by foolip** [comment]
Merging this will be the first test to see if the "Verify Deploy" thing really works end-to-end, since only the new deployment will get updated.

**Comment by foolip** [comment]
The deploy mysteriously failed and inadvertently exercised the deploy verify job. Then a manual deploy worked. So this is done. I'll leave the old VM running for another while, however, in case we need to revert.

**Pull request merged**
